
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class ManagersTbl
{

    public int ManagerID { get; set; }

    public string ManagerName { get; set; }

    public string ManagerHP { get; set; }

    public string ManagerPhone { get; set; }

    public string ManagerAddress { get; set; }

    public string ManagerPhone2 { get; set; }

}

}
