//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundsCustomerProductTbl
    {
        public int RoundsCustomerProductID { get; set; }
        public Nullable<int> RoundsCustomersID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> DelieveredAmount { get; set; }
    }
}
