
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class RoundsTbl
{

    public int RoundsID { get; set; }

    public string RoundName { get; set; }

    public Nullable<System.DateTime> RoundDate { get; set; }

    public Nullable<int> RoundStatus { get; set; }

    public Nullable<int> ManagerID { get; set; }

}

}
