//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TerminalsEntities : DbContext
    {
        public TerminalsEntities()
            : base("name=TerminalsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customers> Customers { get; set; }
        public DbSet<ProductCustomerTbl> ProductCustomerTbl { get; set; }
        public DbSet<RoundsCustomerProductTbl> RoundsCustomerProductTbl { get; set; }
        public DbSet<RoundsCustomerTbl> RoundsCustomerTbl { get; set; }
        public DbSet<RoundsTbl> RoundsTbl { get; set; }
        public DbSet<RoundsUserTbl> RoundsUserTbl { get; set; }
        public DbSet<UsersTbl> UsersTbl { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<AspNetRole> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
