//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VitTbl
    {
        public int VitID { get; set; }
        public Nullable<double> Vit { get; set; }
        public Nullable<System.DateTime> VitDate { get; set; }
    }
}
